# Generated by Django 4.1.1 on 2022-09-23 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_band_description_band_sold_band_type_band_year_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1000)),
                ('sold', models.BooleanField(default=False)),
                ('year', models.IntegerField(null=True)),
                ('type', models.CharField(choices=[('RC', 'Records'), ('CH', 'Clothings'), ('PT', 'Posters'), ('ML', 'Miscellaneous')], max_length=10)),
            ],
        ),
    ]
