# Generated by Django 4.1.1 on 2022-09-23 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_listing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='band',
            name='description',
        ),
        migrations.RemoveField(
            model_name='band',
            name='sold',
        ),
        migrations.RemoveField(
            model_name='band',
            name='type',
        ),
        migrations.RemoveField(
            model_name='band',
            name='year',
        ),
    ]
